title: Exeal
theme: exeal
baseURL: https://www.exeal.com
languageCode: es-es
defaultContentLanguage: es
languages:
  es:
    weight: 1
  en:
    weight: 2
metaDataFormat: yaml
markup:
  goldmark:
    renderer:
      unsafe: true
