title: Exeal
theme: exeal
baseURL: https://www.exeal.com
languageCode: es-es
defaultContentLanguage: es
languages:
  es:
    weight: 1
  en:
    weight: 2
metaDataFormat: yaml
params:
  gtm_id: "GTM-TQGN65PV"
  facebookPixelId: 417415780749470
  facebookDomainVerification: xwbugjbpmp2jwy1y6mzdhe6ga267uz
  hotjarId: 5031744
  hubspotId: 8231847

  navbar:
  - name: "Próximos Eventos"
    url: "/eventos/"
    type: link
  - name: "Recursos"
    type: dropdown
    items:
      - name: "Checklist de Equipos de Alto Rendimiento"
        url: "/checklist-equipos-de-alto-rendimiento/"
      - name: "Habla el idioma del negocio"
        url: "/recursos/habla-el-idioma-del-negocio/"
      - name: "Comunidad de práctica"
        url: "/hacia-la-excelencia/"
      - name: "Blog"
        url: "/blog/"
      - name: "Katas"
        url: "/katas/"

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags
  categories_katas: categories_katas

permalinks:
  categories_katas: /katas/tags/:slug/
